spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gitlab?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

app:
  file-upload: /home/ubuntu/data/gitlab/upload/
  email:
    host: smtp.exmail.qq.com
    port: 465
    username: root@kangyonggan.com
    password: EgUDCpKdaeoL2vts
    expires-in: 10
