spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gitlab?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

gitlab:
  bin-path: /srv/code/gitlab-me-service/src/main/resources/bin
  project-root: /srv/code/repo
  htpasswd-path: /etc/nginx/

app:
  file-upload: /srv/data/gitlab/upload/
  email:
    host: smtp.exmail.qq.com
    port: 465
    username: root@kangyonggan.com
    password: EgUDCpKdaeoL2vts
    expires-in: 10
